[theme]
primaryColor = "#26D07C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EDF6F6"
textColor = "#06415B"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
